version: '3'

services:
  crud-pg12:
    image: postgres:12
    container_name: crud-pg12
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - crud-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud
    networks:
      - services-net
  
      
volumes:
  crud-dbdata:
    external: false

networks:
  services-net:
    driver: bridge
