version: '3'

services:
  crud-pg12:
    image: postgres:12
    container_name: crud-pg12
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - crud-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud
    networks:
      - services-net

  pagamento-pg12:
    image: postgres:12
    container_name: pagamento-pg12
    restart: always
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - pagamento-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagamento
    networks:
      - services-net
  auth-pg12:
    image: postgres:12
    container_name: auth-pg12
    restart: always
    tty: true
    ports:
      - "5434:5432"
    volumes:
      - auth-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    networks:
      - services-net
  
  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-dbdata:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: secret_pass
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

      
volumes:
  crud-dbdata:
    external: false
  pagamento-dbdata:
    external: false
  auth-dbdata:
    external: false
  rabbitmq-dbdata:
    external: false

networks:
  services-net:
    driver: bridge
