server:
  port: 8080
    
spring:
  application:
    name: gateway   
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
        - id: crud
          uri: lb://CRUD
          predicates:
            - Path=/crud/**
        - id: pagamento
          uri: lb://PAGAMENTO
          predicates:
            - Path=/pagamento/**
        
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
      
management.endpoints.web.exposure.include: '*'
