# Server configuration
server:
  port: 8082
  servlet:
    context-path: /pagamento

# Spring Boot configuration
spring:
  application:
    name: pagamento

# JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false      
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/pagamento
    username: postgres
    password: postgres
    
  jmx:
    enabled: false

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
