# Server configuration
server:
  port: 8081
  servlet:
    context-path: /crud

# Spring Boot configuration
spring:
  application:
    name: crud

# JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false      
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: postgres
    
  jmx:
    enabled: false

# Menssage
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  
crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug